MVCAssignment/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace MVCAssignment.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

MVCAssignment/Models/SearchKey.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCAssignment.Models
{
    public class SearchKey
    {

        public string SearchKeyWord { get; set; }
    }
}

MVCAssignment/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MVCAssignment.Areas.HelpPage.Models;

namespace MVCAssignment.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

MVCAssignment/Controllers/TweetController.cs
using Core.Domain;
using CoreServiceMongo.Services;
using MVCAssignment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace MVCAssignment.Controllers
{
    public class TweetController : Controller
    {
        public ActionResult Index()
        {
            TweetService tweets = new TweetService();

            return View(tweets.GetTweets());
        }

        public ActionResult Search(SearchKey obj)
        {
            string query = obj.SearchKeyWord;
            return View(GetTweets(query));
        }
        public IEnumerable<Tweet> GetTweets(string query)
        {
            //This code should probably be moved to a TwitterService or similar.
            using (var webClient = new WebClient())
            {
                //We should also add errorhandling, since the webclient (and parsing) could throw an exception.
                var result = webClient.DownloadString("http://search.twitter.com/search.atom?q=" + Server.UrlEncode(query));
                var tweetDocument = XDocument.Parse(result);
                XNamespace xmlNamespace = "http://www.w3.org/2005/Atom";
                var tweets = from entry in tweetDocument.Descendants(xmlNamespace + "entry")
                             select new Tweet()
                             {
                                 Author = entry.Descendants(xmlNamespace + "name").First().Value,
                                 ID = entry.Element(xmlNamespace + "id").Value,
                                 Text = entry.Element(xmlNamespace + "title").Value,
                                 Time = DateTime.Parse(entry.Element(xmlNamespace + "published").Value)
                             };

                if (tweets != null && tweets.Count() > 0)
                {
                    foreach (Tweet twt in tweets)
                    {
                        TweetService service = new TweetService();
                        service.Create(twt);

                    }
                }
                return tweets.ToArray();
            }
        }
        public ActionResult Start()
        {
            //return View();
            return RedirectToAction("homeApi");
        }

        public ActionResult homeApi()
        {
            return View();
        }

    }
}

MVCAssignment/Controllers/TweetsController.cs
using Core.Domain;
using CoreServiceMongo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Xml.Linq;
using System.Web.Mvc;


namespace MVCAssignment.Controllers
{
    public class TweetsController : ApiController
    {
        
        public IEnumerable<string> Search(string query)
        {
            TweetController obj = new TweetController();
            return obj.GetTweets(query).Select(p => p.Text).AsEnumerable();
           
        }
    }
}

MVCAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
             
                  
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Tweets in Mongo DB", "Index", "Tweet", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Search Twiter", "Start", "Tweet", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCAssignment/Views/Tweet/Index.cshtml
@model IEnumerable<Core.Domain.Tweet>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
   
</p>
<table>
    <tr>
        <th>
            Text
        </th>
        <th>
            Author
        </th>
        <th>
            Time
        </th>
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
       
    </tr>
}

</table>

MVCAssignment/Views/Tweet/Search.cshtml
@model IEnumerable<Core.Domain.Tweet>

@{
    ViewBag.Title = "Twitter search results";
}
<style type="text/css">
.tweet_content
{
    font-weight:bold;
}
.tweet_posted
{
    font-style:italic;
}
</style>
<br />
<br />
<br />
<br />
<ul>
@foreach (var tweet in Model)
{
    <li>
        <div>
            <span class="tweet_author">Tweet from @tweet.Author:</span>
            <span class="tweet_content">@tweet.Text</span>
            <span class="tweet_posted">at @tweet.Time.ToString()</span>
        </div>
    </li>
}
</ul>

MVCAssignment/Views/Tweet/Start.cshtml
@model MVCAssignment.Models.SearchKey

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Search", "Tweet")) {
    @Html.ValidationSummary(true)
    <div>
        <fieldset>
        <legend>Tweet</legend>
            
        <div class="editor-label">
            Search Key Word
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SearchKeyWord)
            
        </div>

       

        <p>
            <input type="submit" value="Search and Save" />

        </p>
    </fieldset>

    </div>
}

MVCAssignment/Views/Tweet/homeApi.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>ASP.NET Web API</title>
    <link href="../../Content/Site.css" rel="stylesheet" />
    
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () { });
            function find() {
                var id = $('#tweetKey').val();
                $.getJSON("/api/Tweets/?query=" + id,
                    function (data) {
                        
                        $('#Tweets').html(buildList(data, false));
                    })
                .fail(
                    function (jqXHR, textStatus, err) {
                        $('#Tweets').html('Error: ' + err);
                    });
            }

            function buildList(data, isSub) {
                var html = (isSub) ? '<div>' : ''; // Wrap with div if true
                html += '<ul>';
                for (item in data) {
                    html += '<li>';
                    if (typeof (data[item].sub) === 'object') { // An array will return 'object'
                        if (isSub) {
                            html += '<a href="' + data[item].link + '">' + data[item].name + '</a>';
                        } else {
                            html += data[item].id; // Submenu found, but top level list item.
                        }
                        html += buildList(data[item].sub, true); // Submenu found. Calling recursively same method (and wrapping it in a div)
                    } else {
                        html += data[item].id // No submenu
                    }
                    html += '</li>';
                }
                html += '</ul>';
                html += (isSub) ? '</div>' : '';
                return html;
            }


        </script>

</head>
<body id="body" >
    <div class="main-content">
   
        <div>
            <label for="tweetskey">Search :</label>
            <input type="text" id="tweetKey" size="5"/>
            <input type="button" value="Search" onclick="find();" />
            <div id="Tweets"> </div>

        </div>
    </div>
</body>
</html>